### ISSUE TITLE
build issue with the latest check-in

### ISSUE THREAD

**Issue by mowrang** [iij/mruby-require#11]
I am trying to build mruby-require to my build. However I get the below error message: 

LD    build/host/bin/mirb 
/home/maryam/installDir/mruby-1.1.0/build/host/lib/libmruby.a(mrb_require.o): In function `unload_so_file':
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:364: undefined reference to `dlopen'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:385: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/build/host/lib/libmruby.a(mrb_require.o): In function `load_so_file':
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:316: undefined reference to `dlopen'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:321: undefined reference to `dlerror'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:339: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:340: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:351: undefined reference to `dlerror'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:319: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
/home/maryam/installDir/mruby-1.1.0/build/host/lib/libmruby.a(mrb_require.o): In function `unload_so_file':
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:364: undefined reference to `dlopen'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:385: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/build/host/lib/libmruby.a(mrb_require.o): In function `load_so_file':
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:316: undefined reference to `dlopen'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:321: undefined reference to `dlerror'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:339: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:340: undefined reference to `dlsym'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:351: undefined reference to `dlerror'
/home/maryam/installDir/mruby-1.1.0/mrbgems/mruby-require-master/src/mrb_require.c:319: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
rake aborted!
Command Failed: [gcc  -o "/home/maryam/installDir/mruby-1.1.0/build/host/bin/mirb" "/home/maryam/installDir/mruby-1.1.0/build/host/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o" "/home/maryam/installDir/mruby-1.1.0/build/host/lib/libmruby.a"  -lm -lreadline                                 ]
Rakefile:67:in `block (4 levels) in <top (required)>'
make: *** [all] Error 1

**Comment by ak-mochi** [comment]
When I checked your error log, you seemed to compile with "mrb_require.c".
But our mruby-require repository (iij/mruby-require) does not have "mrb_require.c".
Please make sure where you got source file from?

**Comment by mowrang** [comment]
Thanks a lot! it is working now. It was my mistake. no issue with your
package.

On Wed, Feb 11, 2015 at 9:55 PM, Akito Mochizuki <notifications@github.com>
wrote:

> When I checked your error log, you seemed to compile with "mrb_require.c".
> But our mruby-require repository (iij/mruby-require) does not have
> "mrb_require.c".
> Please make sure where you got source file from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iij/mruby-require/issues/11#issuecomment-74021633>.
>



-- 
------------------------------------------------------------
Maryam Analui (Owrang)
http://broadband4america.blogspot.com/
