### ISSUE TITLE
open class doesn't work

### ISSUE THREAD

**Issue by yyamano** [iij/mruby-require#13]
open class doesn't work with 'require' method. It creates a class under Kernel module.
It worked before 99568dc5309710f27df05a2db2c13ddad60cc6b9

```
% cat a.rb 
class Foo; end
puts "id=#{Foo.object_id}, inspect=#{Foo.inspect}"

require 'b'

Foo.new.foo
% cat b.rb 
class Foo
  def foo
    puts "FOO"
  end
end

puts "id=#{Foo.object_id}, inspect=#{Foo.inspect}"
% ~/mruby/bin/mruby a.rb 
id=12114713, inspect=Foo
id=12108713, inspect=Kernel::Foo
trace:
	[0] a.rb:6
a.rb:6: undefined method 'foo' for #<Foo:0xb8bfe0> (NoMethodError)
```

**Comment by yyamano** [comment]
I was wrong. It doesn't work with old version of mruby-require too.

**Comment by yyamano** [comment]
https://github.com/mruby/mruby/commit/4523aaec015ff0bf900710efc2ec3411e8841fb1 causes the issue.

**Comment by tsahara** [comment]
Thank you for reporting.  I understand what is the toplevel self better now.
