### ISSUE TITLE
`Kernel` prefix are attached to the namespace

### ISSUE THREAD

**Issue by i110** [iij/mruby-require#14]
preparing foo.rb
```ruby
class Foo end
```

and doing the following:
```ruby
require './foo.rb'
p Foo
```

outputs `Kernel::Foo`, while CRuby outputs `Foo`. Is this behavior what you intended?

Thank you in advance.

**Comment by i110** [comment]
Actually what I want to do is, like the following:

foo_hoge.rb
```ruby
module Foo
  module Hoge
    def create
      Foo::Fuga.new
    end
  end
end
```

main.rb
```ruby
module Foo
  class Fuga end
end

require './foo_hoge.rb'
include Foo::Hoge
p doit
```

the above `main.rb` code show the error below:
```
trace:
        [0] main.rb:6
main.rb:6: uninitialized constant Foo::Hoge (NameError)
```
CRuby doesn't complain about this.

**Comment by tsahara** [comment]
I'm not sure but this issue may be related to the breakage of mruby-eval these days.
https://github.com/mruby/mruby/issues/3429

**Comment by i110** [comment]
Sorry, I missed https://github.com/iij/mruby-require/issues/13. I found that this problem doesn't happen in the latest version.
