### ISSUE TITLE
Why use `mruby-eval`?

### ISSUE THREAD

**Issue by dearblue** [iij/mruby-require#30]
Commit de95b8a27633cd240fef3dfffdcf9ce95884d884 switched from C to an implementation using `mruby-eval`, but I could not guess why.
I would appreciate it if you could tell me why you switched to using `mruby-eval`.

**Comment by tsahara** [comment]
That's because the older C implementation of `require` was heavily dependent on implementation details of the mruby VM.  `eval` version has some incompatibilities with `require` of CRuby but it is better portable across different versions of mruby.

**Comment by dearblue** [comment]
Thank you very much. I understand.

If I wanted to address issues https://github.com/mruby/mruby/issues/5725 and https://github.com/iij/mruby-require/pull/29#issuecomment-1166178804, I couldn't imagine any other way than to implement it in C.
Currently there are unrelated changes mixed in at my hand, so I will try to sort them out and send some.
